package skillbill.application.featuretask

import me.tatarka.inject.annotations.Inject

@Inject
class FeatureTaskRuntimeRunLoopPrimaryCollaborators(
  val drive: FeatureTaskRuntimeRunLoopDrive,
  val phaseRunner: FeatureTaskRuntimeRunLoopPhaseRunner,
  val phaseAttempts: FeatureTaskRuntimeRunLoopPhaseAttempts,
  val launch: FeatureTaskRuntimeRunLoopLaunch,
  val outputVerification: FeatureTaskRuntimeRunLoopOutputVerification,
  val outputPersistence: FeatureTaskRuntimeRunLoopOutputPersistence,
)

@Inject
class FeatureTaskRuntimeRunLoopControlCollaborators(
  val validationGate: FeatureTaskRuntimeRunLoopValidationGate,
  val review: FeatureTaskRuntimeRunLoopReview,
  val checkpoint: FeatureTaskRuntimeRunLoopCheckpoint,
  val planningBranch: FeatureTaskRuntimeRunLoopPlanningBranch,
  val backwardEdge: FeatureTaskRuntimeRunLoopBackwardEdge,
  val attemptSettlement: FeatureTaskRuntimeRunLoopAttemptSettlement,
)

@Inject
class FeatureTaskRuntimeRunLoopSupportCollaborators(
  val recordRejection: FeatureTaskRuntimeRunLoopRecordRejection,
  val repairReceipt: FeatureTaskRuntimeRunLoopRepairReceipt,
  val subtaskCommit: FeatureTaskRuntimeRunLoopSubtaskCommit,
  val transitions: FeatureTaskRuntimeRunLoopTransitions,
)

@Inject
class FeatureTaskRuntimeRunLoopSettlementContinuationCollaborators(
  val attemptSettlementContinued1: FeatureTaskRuntimeRunLoopAttemptSettlementPhaseOutcome,
  val attemptSettlementContinued2: FeatureTaskRuntimeRunLoopAttemptSettlementRepairDispatch,
  val attemptSettlementContinued3: FeatureTaskRuntimeRunLoopAttemptSettlementReceiptFinalize,
)

@Inject
class FeatureTaskRuntimeRunLoopCheckpointContinuationCollaborators(
  val checkpointContinued1: FeatureTaskRuntimeRunLoopCheckpointOwnedPathRemediationEstablish,
  val checkpointContinued2: FeatureTaskRuntimeRunLoopCheckpointRemediationRollback,
  val checkpointContinued3: FeatureTaskRuntimeRunLoopCheckpointRemediationStage,
  val checkpointContinued4: FeatureTaskRuntimeRunLoopCheckpointRollbackIdentity,
  val checkpointContinued5: FeatureTaskRuntimeRunLoopCheckpointSubtaskCommitLedger,
  val checkpointContinued6: FeatureTaskRuntimeRunLoopCheckpointBlocking,
)

@Inject
class FeatureTaskRuntimeRunLoopDriveContinuationCollaborators(
  val driveContinued1: FeatureTaskRuntimeRunLoopDrivePhaseSelection,
  val driveContinued2: FeatureTaskRuntimeRunLoopDriveAttemptLaunch,
  val driveContinued3: FeatureTaskRuntimeRunLoopDriveSettlementGate,
  val driveContinued4: FeatureTaskRuntimeRunLoopDriveTerminalOutcome,
)

@Inject
class FeatureTaskRuntimeRunLoopLaunchContinuationCollaborators(
  val launchContinued1: FeatureTaskRuntimeRunLoopLaunchContentIdentityParse,
  val launchContinued2: FeatureTaskRuntimeRunLoopLaunchAgentSession,
  val launchContinued3: FeatureTaskRuntimeRunLoopLaunchProcessWait,
)

@Inject
class FeatureTaskRuntimeRunLoopOutputVerificationContinuationCollaborators(
  val outputVerificationContinued1: FeatureTaskRuntimeRunLoopOutputVerificationSchemaGate,
  val outputVerificationContinued2: FeatureTaskRuntimeRunLoopOutputVerificationEnvelopeWalk,
  val outputVerificationContinued3: FeatureTaskRuntimeRunLoopOutputVerificationStructuralRepair,
  val outputVerificationContinued4: FeatureTaskRuntimeRunLoopOutputVerificationDuplicateKeyMerge,
  val outputVerificationContinued5: FeatureTaskRuntimeRunLoopOutputVerificationReceiptAssembly,
)

@Inject
class FeatureTaskRuntimeRunLoopPhaseContinuationCollaborators(
  val phaseAttemptsContinued1: FeatureTaskRuntimeRunLoopPhaseAttemptsAttemptBudget,
  val phaseAttemptsContinued2: FeatureTaskRuntimeRunLoopPhaseAttemptsRetrySchedule,
  val phaseAttemptsContinued3: FeatureTaskRuntimeRunLoopPhaseAttemptsBackoffGate,
  val phaseRunnerContinued1: FeatureTaskRuntimeRunLoopPhaseRunnerPhaseDispatch,
  val phaseRunnerContinued2: FeatureTaskRuntimeRunLoopPhaseRunnerMutatingPhase,
  val phaseRunnerContinued3: FeatureTaskRuntimeRunLoopPhaseRunnerVerifyingPhase,
)

@Inject
class FeatureTaskRuntimeRunLoopValidationGateContinuationCollaborators(
  val validationGateContinued1: FeatureTaskRuntimeRunLoopValidationGateCollectCommand,
  val validationGateContinued2: FeatureTaskRuntimeRunLoopValidationGateBuildCommand,
  val validationGateContinued3: FeatureTaskRuntimeRunLoopValidationGateSkillBillValidate,
  val validationGateContinued4: FeatureTaskRuntimeRunLoopValidationGateAgnixValidate,
)

@Inject
class FeatureTaskRuntimeRunLoopCoreContinuationCollaborators(
  val settlement: FeatureTaskRuntimeRunLoopSettlementContinuationCollaborators,
  val checkpoint: FeatureTaskRuntimeRunLoopCheckpointContinuationCollaborators,
  val drive: FeatureTaskRuntimeRunLoopDriveContinuationCollaborators,
  val launch: FeatureTaskRuntimeRunLoopLaunchContinuationCollaborators,
)

@Inject
class FeatureTaskRuntimeRunLoopGateContinuationCollaborators(
  val outputVerification: FeatureTaskRuntimeRunLoopOutputVerificationContinuationCollaborators,
  val phase: FeatureTaskRuntimeRunLoopPhaseContinuationCollaborators,
  val validationGate: FeatureTaskRuntimeRunLoopValidationGateContinuationCollaborators,
)
