package skillbill.db.workflow

import skillbill.contracts.workflow.FEATURE_TASK_RUNTIME_CONTRACT_VERSION
import skillbill.contracts.workflow.FeatureTaskRuntimePhaseOutputSchemaPaths
import skillbill.error.InvalidGoalPlanningPreparationSchemaError
import skillbill.ports.goalrunner.model.GoalPlanningPreparationRecord
import skillbill.ports.goalrunner.model.GoalPlanningPreparationState

internal fun requirePreparedEnvelope(record: GoalPlanningPreparationRecord) {
  val label = "${record.parentGoalWorkflowId}#${record.subtaskId}"
  val failure = envelopeFailure(record) ?: provenanceFailure(record)
  failure?.let {
    throw InvalidGoalPlanningPreparationSchemaError(sourceLabel = label, fieldPath = "", reason = it)
  }
}

internal fun recoveryIdentityFailure(stored: StoredRecoveryIdentity, record: GoalPlanningPreparationRecord): String? {
  if (stored.normalizedIssueKey != record.normalizedIssueKey ||
    stored.repositoryIdentity != record.repositoryIdentity
  ) {
    return incompatibleIdentityReason(
      stored.normalizedIssueKey,
      stored.repositoryIdentity,
      record.normalizedIssueKey,
      record.repositoryIdentity,
    )
  }
  val incomingTuple = record.provenance.asRecoveryTuple()
  if (stored.provenanceTuple != incomingTuple) {
    return incompatibleProvenanceReason(stored.provenanceTuple, incomingTuple)
  }
  return null
}

private fun envelopeFailure(record: GoalPlanningPreparationRecord): String? = when {
  record.contractVersion != LEGACY_GOAL_PLANNING_PREPARATION_CONTRACT_VERSION ->
    "contract_version must be '$LEGACY_GOAL_PLANNING_PREPARATION_CONTRACT_VERSION' " +
      "but was '${record.contractVersion}'"
  record.subtaskId < 1 -> "subtask_id must be a positive integer"
  record.parentGoalWorkflowId.isBlank() -> "parent_goal_workflow_id is required"
  record.normalizedIssueKey.isBlank() -> "normalized_issue_key is required"
  record.repositoryIdentity.isBlank() -> "repository_identity is required"
  record.governedSubSpecPath.isBlank() -> "governed_sub_spec_path is required"
  record.preparationStatus != GoalPlanningPreparationState.PREPARED ->
    "preparation_status must be 'prepared' to checkpoint a pair"
  record.preplanPayload.isBlank() -> "preplan_payload is required"
  record.planPayload.isBlank() -> "plan_payload is required"
  else -> null
}

private fun provenanceFailure(record: GoalPlanningPreparationRecord): String? = when {
  record.provenance.parentSpecHash.isBlank() -> "provenance.parent_spec_hash is required"
  record.provenance.subSpecHash.isBlank() -> "provenance.sub_spec_hash is required"
  record.provenance.decompositionManifestHash.isBlank() -> "provenance.decomposition_manifest_hash is required"
  record.provenance.phaseOutputContractId != FeatureTaskRuntimePhaseOutputSchemaPaths.EXPECTED_SCHEMA_ID ->
    "provenance.phase_output_contract_id must be the feature-task-runtime phase output schema id"
  record.provenance.phaseOutputContractVersion != FEATURE_TASK_RUNTIME_CONTRACT_VERSION ->
    "provenance.phase_output_contract_version must be '$FEATURE_TASK_RUNTIME_CONTRACT_VERSION'"
  else -> null
}

private fun incompatibleIdentityReason(
  storedIssueKey: String,
  storedRepo: String,
  incomingIssueKey: String,
  incomingRepo: String,
): String = "stored normalized_issue_key/repository_identity '$storedIssueKey/$storedRepo'" +
  " differs from incoming '$incomingIssueKey/$incomingRepo'" +
  " (normalized_issue_key/repository_identity mismatch indicates a different goal or repository);" +
  " a prepared pair is immutable and cannot be regenerated by resume."

private fun incompatibleProvenanceReason(stored: List<String>, incoming: List<String>): String =
  "stored provenance ${stored.joinToString("/")}" +
    " differs from incoming ${incoming.joinToString("/")}" +
    " (sub_spec_hash/decomposition_manifest_hash mismatch indicates a different spec);" +
    " a prepared pair is immutable and cannot be regenerated by resume."

internal const val LEGACY_GOAL_PLANNING_PREPARATION_CONTRACT_VERSION = "0.1"
