package skillbill.cli.goal

internal const val DEFAULT_GOAL_PROGRESS_IDLE_TIMEOUT_MINUTES = 10

internal const val DEFAULT_GOAL_WATCH_INTERVAL_SECONDS = 5
internal const val DEFAULT_GOAL_WATCH_REFRESHES = 0
internal const val IDLE_STOP_CONSECUTIVE_REFRESHES = 3
internal const val MILLIS_PER_SECOND = 1_000L
internal const val RUNTIME_EXECUTABLE_ENV = "SKILL_BILL_RUNTIME_EXECUTABLE"
internal const val RUNTIME_CLASSPATH_ENV = "SKILL_BILL_RUNTIME_CLASSPATH"
internal const val RUNTIME_PATH_SEPARATOR_ENV = "SKILL_BILL_PATH_SEPARATOR"
