package skillbill.application.workflow.model

import skillbill.goalrunner.model.GoalObservabilityProgressInput as PProgressInput
import skillbill.goalrunner.model.GoalObservabilityRuntimeEventInput as PRuntimeEventInput
import skillbill.goalrunner.model.GoalObservabilityWorktreeActivity as PWorktreeActivity
import skillbill.ports.workflow.model.WorkflowFamily as PWorkflowFamily

typealias WorkflowFamily = PWorkflowFamily
typealias GoalObservabilityProgressInput = PProgressInput
typealias GoalObservabilityRuntimeEventInput = PRuntimeEventInput
typealias GoalObservabilityWorktreeActivity = PWorktreeActivity
