org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.parallel=true
org.gradle.workers.max=8
org.gradle.vfs.watch=true
org.gradle.jvmargs=-Xmx8g -Xms1g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx6g -Xms512m -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
kotlin.incremental=true
org.gradle.warning.mode=all
kotlin.code.style=official
