package skillbill.review.context.model

const val REVIEW_DIGEST_HEX_LENGTH: Int = 64

const val REVIEW_MIN_ORDER_INDEX: Int = 0

const val REVIEW_SYNTHETIC_UNIT_ORDER_INDEX: Int = 0

const val REVIEW_MIN_COMMIT_COUNT: Int = 1

const val REVIEW_MIN_HUNK_LINE: Int = 0

const val REVIEW_BUNDLE_SEGMENT_ID_PAD_WIDTH: Int = 3

const val REVIEW_MIN_LANE_BUDGET_SEGMENT_COUNT: Int = 1

const val REVIEW_BUNDLE_MEASUREMENT_PLACEHOLDER_BYTES: Long = 1

const val REVIEW_MIN_SEGMENT_MEASURED_BYTES: Long = 1
