package skillbill.ports.telemetry

import skillbill.review.model.ReviewStageDegradationMeasurement
import skillbill.workflow.taskruntime.model.FeatureTaskRuntimeDiagnosticDegradationMeasurement
import skillbill.workflow.taskruntime.model.FeatureTaskRuntimeProjectionMeasurement
import skillbill.workflow.taskruntime.model.FeatureTaskRuntimeRejectionMeasurement
import skillbill.workflow.taskruntime.model.FeatureTaskRuntimeSharedEvidenceMeasurement

interface FeatureTaskRuntimeTelemetryMeasurementRepository {
  fun featureTaskRuntimeProjectionMeasurement(record: FeatureTaskRuntimeProjectionMeasurement) = Unit

  fun featureTaskRuntimeSharedEvidence(record: FeatureTaskRuntimeSharedEvidenceMeasurement) = Unit

  fun featureTaskRuntimeRejection(record: FeatureTaskRuntimeRejectionMeasurement) = Unit

  fun featureTaskRuntimeDiagnosticDegradation(record: FeatureTaskRuntimeDiagnosticDegradationMeasurement) = Unit
}

interface ReviewStageTelemetryMeasurementRepository {
  fun reviewStageDegradation(record: ReviewStageDegradationMeasurement) = Unit
}

interface LifecycleTelemetryRepository :
  FeatureTaskRuntimeTelemetryMeasurementRepository,
  ReviewStageTelemetryMeasurementRepository,
  FeatureTaskRuntimeLifecycleTelemetryRepository,
  QualityCheckLifecycleTelemetryRepository,
  FeatureVerifyLifecycleTelemetryRepository,
  PrDescriptionLifecycleTelemetryRepository,
  GoalLifecycleTelemetryRepository
