package skillbill.ports.goalrunner.persistence

import skillbill.ports.goalrunner.persistence.model.GoalRunnerChildRepairApplyRequest
import skillbill.ports.goalrunner.persistence.model.GoalRunnerChildRepairApplyResult
import skillbill.ports.goalrunner.persistence.model.GoalRunnerChildRepairDiagnoseRequest
import skillbill.ports.goalrunner.persistence.model.GoalRunnerChildWedgeDiagnosis

interface GoalRunnerChildRepairRunnerPort {
  fun diagnose(request: GoalRunnerChildRepairDiagnoseRequest): GoalRunnerChildWedgeDiagnosis

  fun apply(request: GoalRunnerChildRepairApplyRequest): GoalRunnerChildRepairApplyResult
}
