build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
