build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

comments:
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7
  NestedBlockDepth:
    active: true
    threshold: 6

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable

style:
  MaxLineLength:
    active: true
    maxLineLength: 120
  ReturnCount:
    active: true
    max: 4
